global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ivan_kazakov'
