version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    networks:
      - back_net
    env_file:
      - .env

  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
    env_file:
      - .env
    

  post:
    image: ${USERNAME}/post:latest
    networks:
      - back_net
      - front_net
    env_file:
      - .env

  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - back_net
      - front_net
    env_file:
      - .env

volumes:
  post_db:

networks:
  reddit:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
