version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    networks:
      - back_net
    env_file:
      - .env

  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
    env_file:
      - .env
    

  post:
    image: ${USERNAME}/post:latest
    networks:
      - back_net
      - front_net
    env_file:
      - .env

  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - back_net
      - front_net
    env_file:
      - .env
      
  prometheus:
    image: ${USERNAME}/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

volumes:
  prometheus_data:
  post_db:

networks:
  reddit:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
