kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: Kxazhjfe4SX2EmKNYK9BYHzdgrvKW7jrFHIKMX4MT2A=
      - identity: {}
